### ISSUE TITLE
Jenkins Wrapper Failing with "anscii" error on 2016

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave-ci/test-infra#169]
```
Starting polling for our job to start
 . Waiting for job to start because : In the quiet period. Expires in 4.8 sec
 . Waiting for job to start because : In the quiet period. Expires in 2.6 sec
 . Waiting for job to start because : In the quiet period. Expires in 0.42 sec
 . Waiting for job to start because : Finished waiting
 . Waiting for job to start because : Traceback (most recent call last):
  File "/hack/jenkins_bootstrap.py", line 177, in <module>
    myrigger.main()
  File "/hack/jenkins_bootstrap.py", line 170, in main
    job_number = self.waiting_for_job_to_start(queue_url)
  File "/hack/jenkins_bootstrap.py", line 97, in waiting_for_job_to_start
    print " . Waiting for job to start because :", queue_request.json().get("why")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 39: ordinal not in range(128)
```

**Comment by BRMcLaren** [comment]
/sig/test-infra
